# Auto-generated by install.sh
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/1D_A_exp_fft+cgemm+ifft/build
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/1D_B_exp_fused_fft_cgemm+ifft/build
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/1D_C_exp_fft+fused_cgemm_ifft/build
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/1D_D_exp_fused_fft_cgemm_ifft/build
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/1D_E_baseline/build
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/2D_A_exp_fft+cgemm+ifft/build
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/2D_B_exp_fused_fft_cgemm+ifft/build
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/2D_C_exp_fft+fused_cgemm_ifft/build
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/2D_D_exp_fused_fft_cgemm_ifft/build
export PATH=$PATH:/global/homes/s/swu264/TurboFNO/fusion_variants/2D_E_baseline/build
