#!/bin/bash

set -e

# 确保环境变量 PROJECT_ROOT 已设置
if [ -z "$PROJECT_ROOT" ]; then
  echo "❌ Please set PROJECT_ROOT first:"
  echo "   export PROJECT_ROOT=/path/to/TurboFNO"
  exit 1
fi

VARIANT_DIRS=(
  "1D_A_exp_fft+cgemm+ifft"
  "1D_B_exp_fused_fft_cgemm+ifft"
  "1D_C_exp_fft+fused_cgemm_ifft"
  "1D_D_exp_fused_fft_cgemm_ifft"
  "1D_E_baseline"
  "2D_A_exp_fft+cgemm+ifft"
  "2D_B_exp_fused_fft_cgemm+ifft"
  "2D_C_exp_fft+fused_cgemm_ifft"
  "2D_D_exp_fused_fft_cgemm_ifft"
  "2D_E_baseline"
)

# === clinea ===
if [ "$1" == "clean" ]; then
  echo "🧹 Cleaning all build directories..."
  for dir in "${VARIANT_DIRS[@]}"; do
    if [ -d "fusion_variants/$dir/build" ]; then
      echo "❌ Removing $dir/build ..."
      rm -rf "fusion_variants/$dir/build"
    fi
  done
  echo "✅ All build directories removed."
  echo "🧼 Removing generated envpath.sh ..."
  rm -f envpath.sh
  echo "✅ Done."
  exit 0
fi

# === 编译所有 variants ===
echo "🛠  Starting compilation of all TurboFNO variants..."

# 清空或初始化 envpath.sh
echo "# Auto-generated by install.sh" > envpath.sh

# Set USE_HIP=1 to build for ROCm/HIP instead of CUDA. The target GPU is
# auto-detected from the build host; set CMAKE_HIP_ARCHITECTURES (e.g.
# CMAKE_HIP_ARCHITECTURES=gfx1100) to build for a different AMD GPU.
if [ "${USE_HIP:-0}" = "1" ]; then
  CMAKE_FLAGS="-DUSE_HIP=ON"
  [ -n "${CMAKE_HIP_ARCHITECTURES}" ] && CMAKE_FLAGS="${CMAKE_FLAGS} -DCMAKE_HIP_ARCHITECTURES=${CMAKE_HIP_ARCHITECTURES}"
  [ -n "${CMAKE_HIP_COMPILER}" ] && CMAKE_FLAGS="${CMAKE_FLAGS} -DCMAKE_HIP_COMPILER=${CMAKE_HIP_COMPILER}"
else
  CMAKE_FLAGS=""
fi

for dir in "${VARIANT_DIRS[@]}"; do
  echo "🔹 Building $dir ..."
  cd "fusion_variants/$dir"
  mkdir -p build && cd build
  cmake .. $CMAKE_FLAGS
  make -j
  echo "export PATH=\$PATH:$(pwd)" >> "$PROJECT_ROOT/envpath.sh"
  cd ../../..
done

echo "✅ All variants built successfully!"
echo "📦 PATH entries for executables saved to: $PROJECT_ROOT/envpath.sh"
echo "📌 To use them, run:"
echo "    source $PROJECT_ROOT/envpath.sh"
